name: farm_bracket
version: 1.0.0+1
description: A new Flutter project for FarmBracket
publish_to: 'none'

environment:
  sdk: '^3.8.0'

dependencies:
  badges: ^3.1.2
  flutter:
    sdk: flutter
  geolocator: ^14.0.2
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  # supabase_flutter: ^2.9.1
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.4.1
  intl: ^0.20.2
  hive: ^2.2.3
  auto_route: ^10.1.2
  flutter_riverpod: ^2.6.1
  # firebase_auth: ^6.0.1
  google_maps_flutter: ^2.5.0
  image_picker: ^1.0.7
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  lottie: ^3.3.1
  file_picker: ^10.3.2
  qr_flutter: ^4.1.0
  geocoding: ^4.0.0
  shimmer: ^3.0.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  mockito: ^5.4.2
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  generate: true